trigger: none

pr:
  branches:
    include:
      - main
      - test
  paths:
    include:
      - infra/**
      - .azure/**

pool:
  vmImage: ubuntu-latest

variables:
  - group: vg-networking-dev
  TF_VERSION: "1.8.5"

stages:
  - stage: Validate
    displayName: Validate (PR)
    jobs:
      - job: TerraformValidate
        displayName: Terraform Validate + Plan
        steps:
          - task: Bash@3
            displayName: Install Terraform
            inputs:
              targetType: inline
              script: |
                wget -q https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
                unzip -q terraform_$(TF_VERSION)_linux_amd64.zip
                sudo mv terraform /usr/local/bin/
                terraform version

          - template: ../templates/steps-validate.yml
            parameters:
              serviceConnection: sc-azure-dev
              tfVarsFile: dev.tfvars
              backendResourceGroup: $(tf_resource_group)
              backendStorageAccount: $(tf_storage_account)
              backendContainer: $(tf_container)
